### ISSUE TITLE
Missing include.

### ISSUE THREAD

**Issue by xerxes-at** [GameProgressive/RetroSpyServerCXX#3]
Hi, I tried to build this under Ubuntu 18.04 and VS 2017. I kinda hoped the mdk includes are a Microsoft thingy but nope, I also can't seem to find it through google. Would be nice if you could point me in the correct direction.

**Comment by arves100** [comment]
Hello, MDK it's GameProgressive project, I suggest you to clone
https://github.com/GameProgressive/GameSpyEmulator. It contains all the
projects that are required for building RetroSpy.

Il dom 26 ago 2018, 02:52 xerxes-at <notifications@github.com> ha scritto:

**Comment by xerxes-at** [comment]
Thanks a lot.
